# Generated by Django 6.1.1 on 2026-09-07 05:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngram_size', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Taille du n-gramme')),
                ('normalization', models.CharField(choices=[('lowercase', 'Minuscules'), ('accents', 'Suppression des accents'), ('spaces', 'Normalisation des espaces'), ('full', 'Normalisation complète')], default='lowercase', max_length=20, verbose_name='Normalisation')),
                ('alert_threshold', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Seuil d'alerte (%)")),
                ('status', models.CharField(choices=[('pending', 'En cours'), ('completed', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngram_size', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Taille du n-gramme')),
                ('normalisation', models.BooleanField(default=True, verbose_name='Normalisation du texte')),
                ('alert_threshold', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Seuil d'alerte (%)")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du document')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='Fichier')),
                ('file_extension', models.CharField(max_length=10, verbose_name='Extension')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='Taille (octets)')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de mots')),
                ('content', models.TextField(blank=True, verbose_name='Texte extrait')),
                ('text_extracted', models.BooleanField(default=False, verbose_name='Texte extrait ?')),
                ('status', models.CharField(choices=[('ready', 'Prêt'), ('pending', 'À extraire')], default='pending', max_length=20, verbose_name='Statut')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'importation")),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Importé par')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField(default=0.0, verbose_name='Similarité (%)')),
                ('common_ngrams', models.IntegerField(default=0, verbose_name='N-grammes communs')),
                ('total_ngrams_doc1', models.IntegerField(default=0, verbose_name='Total n-grammes doc 1')),
                ('total_ngrams_doc2', models.IntegerField(default=0, verbose_name='Total n-grammes doc 2')),
                ('matches', models.IntegerField(default=0, verbose_name='Correspondances')),
                ('status', models.CharField(choices=[('conforme', 'Conforme'), ('revision', 'À réviser'), ('plagiat', 'Plagiat')], default='conforme', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='textsim.analysis', verbose_name='Analyse')),
                ('document1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='textsim.document', verbose_name='Document 1')),
                ('document2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='textsim.document', verbose_name='Document 2')),
            ],
            options={
                'ordering': ['-similarity'],
            },
        ),
        migrations.AddField(
            model_name='analysis',
            name='documents',
            field=models.ManyToManyField(related_name='analyses', to='textsim.document', verbose_name='Documents'),
        ),
        migrations.CreateModel(
            name='MatchingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('text1', models.TextField(blank=True, verbose_name='Texte doc 1')),
                ('text2', models.TextField(blank=True, verbose_name='Texte doc 2')),
                ('similarity', models.FloatField(default=0.0, verbose_name='Similarité du passage (%)')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='textsim.comparison', verbose_name='Comparaison')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
