# Generated by Django 6.1.1 on 2026-09-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textsim', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('username', models.CharField(max_length=150, verbose_name="Nom d'utilisateur")),
                ('password_hash', models.CharField(max_length=255, verbose_name='Mot de passe (empreinte)')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Code (empreinte SHA-256)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(verbose_name='Expiration')),
                ('used', models.BooleanField(default=False, verbose_name='Utilisé ?')),
            ],
            options={
                'verbose_name': 'Inscription en attente',
                'verbose_name_plural': 'Inscriptions en attente',
                'ordering': ['-created_at'],
            },
        ),
    ]
